### ISSUE TITLE
CSV importer Part I

### ISSUE THREAD

**Issue by DanielePalombo** [nebulab/solidus#35]
https://github.com/nebulab/solidus/issues/31

Rel https://github.com/nebulab/solidus/issues/31 First part

Make a CSV importer upload products, orders, and customers.

We think that the importer will be used only for the first import. So we can skip the check to update the entities.

**Describe alternatives you've considered**
We can create a Converter from CSV to JSON to reuse the existing importers.

**Additional context**
[existing importers](https://github.com/solidusio/solidus/blob/master/core/lib/spree/core/importer)

**Comment by DanielePalombo** [comment]
Some details after meeting:

https://github.com/orgs/nebulab/projects/3#card-30533925

- same CSV formats as Shopify
- using ActiveJob
- other extensions can add their own jobs
- admin UI to upload CSV files
- log importing events and errors with solidus Log

owners: @blocknotes @DanielePalombo @elia

**Comment by blocknotes** [comment]
_Work In Progress_

Admin UI notes:
- upload CSV files
- monitor imports status
- check imports results (Spree::Log entities?)

**Comment by blocknotes** [comment]
Extension project ➡️https://github.com/nebulab/solidus_importer
